### ISSUE TITLE
How to run the code without connecting https://huggingface.com ?

### ISSUE THREAD

**Issue by ZYBOBO** [briannlongzhao/DreamDistribution#3]
Hello, I am a beginner to the diffusion model. 
I failed to run your codes due to an unstable Internet connection to https://huggingface.com, could you tell me how to modify the code to train the model locally using the pre-trained diffusion model I downloaded?

**Comment by briannlongzhao** [comment]
Hi, if you manually downloaded the pretrained diffusion model, you could simply provide the path as the argument of --pretrained_model_name_or_path

**Comment by ZYBOBO** [comment]
Thanks for your reply~
I've downloaded the pre-trained diffusion model (i.e., stable-diffusion-2-1.ckpt) and tried it, but it still fails with OSError:[Errno 101] Network is unreachable. (urllib3/util/connection.py  line 85 in create_connection raise err)
